CREATE DATABASE UserInput;

USE UserInput;

CREATE table Users(
Name VARCHAR(50) NOT NULL,
Pass CHAR(60) NOT NULL,
Question VARCHAR(100) NOT NULL,
Answer VARCHAR(50) NOT NULL,
Email VARCHAR(320) NOT NULL,
Fname VARCHAR(50) NOT NULL,
Lname VARCHAR(50) NOT NULL,
Sex VARCHAR(10) NOT NULL,
Birthday DATE NOT NULL,
Picture VARCHAR(50) NOT NULL,
CONSTRAINT PK_Name PRIMARY KEY(Name) 
);